In [2]:
import numpy as np
import pandas as pd

In [3]:
# Create Dataframe
d_data = pd.DataFrame({'Values' : ['Males', 'Female'],
                    'East' : [50,550],
                    'West' : [142,351],
                   'North' : [131,480],
                   'South' : [70,350]
                  })

In [4]:
d_data

Values  East  West  North  South
0   Males    50   142    131     70
1  Female   550   351    480    350

In [5]:
# We will choose Chi-square statistics as we need to compare two categorial variables i.e Male and Female
# H0 - Male and Female ratio is same
# H0 - Male and Female ratio is not same


In [6]:
d_data_values = d_data.iloc[:,1:]

In [7]:
d_data_values

East  West  North  South
0    50   142    131     70
1   550   351    480    350

In [8]:
d_data_values.values

array([[ 50, 142, 131,  70],
       [550, 351, 480, 350]], dtype=int64)

In [9]:
d_data_values.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   East    2 non-null      int64
 1   West    2 non-null      int64
 2   North   2 non-null      int64
 3   South   2 non-null      int64
dtypes: int64(4)
memory usage: 192.0 bytes


In [12]:
from scipy import stats
val = stats.chi2_contingency(d_data_values)

In [13]:
val

(80.27295426602495,
 2.682172557281901e-17,
 3,
 array([[111.01694915,  91.21892655, 113.05225989,  77.71186441],
        [488.98305085, 401.78107345, 497.94774011, 342.28813559]]))

In [14]:
no_of_rows=len(d_data_values.iloc[0:2,0])
no_of_columns=len(d_data_values.iloc[0,0:4])
degree_of_f=(no_of_rows-1)*(no_of_columns-1)
print('Degree of Freedom=',degree_of_f)

Degree of Freedom= 3


In [15]:
Expected_value = val[3]

In [16]:
Expected_value

array([[111.01694915,  91.21892655, 113.05225989,  77.71186441],
       [488.98305085, 401.78107345, 497.94774011, 342.28813559]])

In [17]:
from scipy.stats import chi2
chi_square=sum([(o-e)**2/e for o,e in zip(d_data_values.values,Expected_value)])
chi_square_statestic=chi_square[0]+chi_square[1]
chi_square_statestic

75.83769204761725

In [18]:
critical_value=chi2.ppf(0.95,3)
critical_value

7.814727903251179

In [19]:
if chi_square_statestic >= critical_value:
	print('Variables are dependent')
else:
	print('Variables are independent')

Variables are dependent
