In [10]:
import pandas as pd
import numpy as np
from scipy import stats

In [4]:
df = pd.read_csv("C:/Users/MRIGESHA/Desktop/EXCELR/Assignments/Hypothesis Testing/Costomer+OrderForm.csv")

In [5]:
df

Phillippines   Indonesia       Malta       India
0     Error Free  Error Free   Defective  Error Free
1     Error Free  Error Free  Error Free   Defective
2     Error Free   Defective   Defective  Error Free
3     Error Free  Error Free  Error Free  Error Free
4     Error Free  Error Free   Defective  Error Free
..           ...         ...         ...         ...
295   Error Free  Error Free  Error Free  Error Free
296   Error Free  Error Free  Error Free  Error Free
297   Error Free  Error Free   Defective  Error Free
298   Error Free  Error Free  Error Free  Error Free
299   Error Free   Defective   Defective  Error Free

[300 rows x 4 columns]

In [6]:
df1 = df['Phillippines'].value_counts(),df['Indonesia'].value_counts(),df['Malta'].value_counts(),df['India'].value_counts()

In [7]:
df1

(Error Free    271
 Defective      29
 Name: Phillippines, dtype: int64,
 Error Free    267
 Defective      33
 Name: Indonesia, dtype: int64,
 Error Free    269
 Defective      31
 Name: Malta, dtype: int64,
 Error Free    280
 Defective      20
 Name: India, dtype: int64)

In [19]:
# Create Dataframe
d_data = pd.DataFrame({'Values' : ['Error Free', 'Defective'],
                    'Phillippines' : [271,29],
                    'Indonesia' : [267,33],
                   'Malta' : [269,31],
                   'India' : [280,20]
                  })

In [20]:
d_data

Values  Phillippines  Indonesia  Malta  India
0  Error Free           271        267    269    280
1   Defective            29         33     31     20

In [ ]:
# We will choose Chi-square statistics as we need to compare two categorial variables i.e Error Free and Defective
# H0 - Mean of Defective forms are same for all countries
# H1 - Mean of Defective forms are different for all countries


In [21]:
d_data_values = d_data.iloc[:,1:]

In [22]:
d_data_values

Phillippines  Indonesia  Malta  India
0           271        267    269    280
1            29         33     31     20

In [23]:
d_data_values.values

array([[271, 267, 269, 280],
       [ 29,  33,  31,  20]], dtype=int64)

In [24]:
d_data_values.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Phillippines  2 non-null      int64
 1   Indonesia     2 non-null      int64
 2   Malta         2 non-null      int64
 3   India         2 non-null      int64
dtypes: int64(4)
memory usage: 192.0 bytes


In [25]:
val = stats.chi2_contingency(d_data_values)

In [26]:
val

(3.858960685820355,
 0.2771020991233135,
 3,
 array([[271.75, 271.75, 271.75, 271.75],
        [ 28.25,  28.25,  28.25,  28.25]]))

In [27]:
no_of_rows=len(d_data_values.iloc[0:2,0])
no_of_columns=len(d_data_values.iloc[0,0:4])
degree_of_f=(no_of_rows-1)*(no_of_columns-1)
print('Degree of Freedom=',degree_of_f)

Degree of Freedom= 3


In [31]:
Expected_value = val[3]

In [32]:
Expected_value

array([[271.75, 271.75, 271.75, 271.75],
       [ 28.25,  28.25,  28.25,  28.25]])

In [34]:
from scipy.stats import chi2
chi_square=sum([(o-e)**2/e for o,e in zip(d_data_values.values,Expected_value)])
chi_square_statestic=chi_square[0]+chi_square[1]
chi_square_statestic

0.9036806669326146

In [35]:
critical_value=chi2.ppf(0.95,3)
critical_value

7.814727903251179

In [37]:
if chi_square_statestic >= critical_value:
	print('Variables are dependent')
else:
	print('Variables are independent')

Variables are independent
